services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - appnet

volumes:
  pgdata:
  static_volume:
  media_volume:

networks:
  appnet:
    external: true