# Generated by Django 5.2.3 on 2025-07-06 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['file_type'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='usertodocs',
            options={'verbose_name': 'Пользователь‑Документ', 'verbose_name_plural': 'Пользователи‑Документы'},
        ),
        migrations.AddField(
            model_name='docs',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='docs_app.docs', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_price',
            field=models.FloatField(verbose_name='Стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='size_file',
            field=models.FloatField(help_text='Размер файла в КБ', verbose_name='Размер (КБ)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='file_type',
            field=models.CharField(help_text='Расширение (jpg, png, pdf...)', max_length=10, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(help_text='Цена за 1 КБ', verbose_name='Цена (руб/КБ)'),
        ),
        migrations.AlterField(
            model_name='usertodocs',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_users', to='docs_app.docs', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='usertodocs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_docs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
